"""initial schema

Revision ID: 835944c91780
Revises:
Create Date: 2026-03-14 03:51:26.176500

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op  # type: ignore[attr-defined]

# revision identifiers, used by Alembic.
revision: str = "835944c91780"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("color", sa.Text(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.CheckConstraint("color LIKE '#%'", name="ck_categories_color_hex"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_categories_id"), "categories", ["id"], unique=False)
    op.create_table(
        "habits",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("frequency_type", sa.Text(), nullable=False),
        sa.Column("frequency_target", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.Column("archived_at", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "frequency_type IN ('daily', 'weekly', 'monthly')", name="ck_habits_frequency_type"
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_habits_id"), "habits", ["id"], unique=False)
    op.create_table(
        "habit_completions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("habit_id", sa.Integer(), nullable=False),
        sa.Column("completed_at", sa.Text(), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.CheckConstraint("source IN ('manual', 'todo')", name="ck_habit_completions_source"),
        sa.ForeignKeyConstraint(
            ["habit_id"],
            ["habits.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_habit_completions_id"), "habit_completions", ["id"], unique=False)
    op.create_table(
        "todos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("habit_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("priority", sa.Text(), nullable=False),
        sa.Column("due_date", sa.Text(), nullable=False),
        sa.Column("completed_at", sa.Text(), nullable=False),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.CheckConstraint("priority IN ('low', 'medium', 'high')", name="ck_todos_priority"),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["habit_id"],
            ["habits.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_todos_id"), "todos", ["id"], unique=False)
    op.create_index(
        "ix_habit_completions_habit_id_completed_at",
        "habit_completions",
        ["habit_id", "completed_at"],
    )
    op.create_index("ix_todos_completed_at", "todos", ["completed_at"])
    op.create_index("ix_todos_due_date", "todos", ["due_date"])
    op.create_index("ix_habits_category_id", "habits", ["category_id"])
    op.create_index("ix_todos_category_id", "todos", ["category_id"])
    op.create_index("ix_todos_habit_id", "todos", ["habit_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_todos_id"), table_name="todos")
    op.drop_table("todos")
    op.drop_index(op.f("ix_habit_completions_id"), table_name="habit_completions")
    op.drop_table("habit_completions")
    op.drop_index(op.f("ix_habits_id"), table_name="habits")
    op.drop_table("habits")
    op.drop_index(op.f("ix_categories_id"), table_name="categories")
    op.drop_table("categories")
    op.drop_index("ix_habit_completions_habit_id_completed_at", "habit_completions")
    op.drop_index("ix_todos_completed_at", "todos")
    op.drop_index("ix_todos_due_date", "todos")
    op.drop_index("ix_habits_category_id", "habits")
    op.drop_index("ix_todos_category_id", "todos")
    op.drop_index("ix_todos_habit_id", "todos")
    # ### end Alembic commands ###
